name: Install and Build and Deploy
on:
  push:
    branches: [ master ]
  pull_request:
    types:
      - closed

jobs:
  build-app:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout chat-box-vue
        uses: actions/checkout@v2
        with:
          repository: 'Claudia1991/chat-box-vue'
          token: ${{ secrets.API_TOKEN_GITHUB }}

      - name: Configure OpenSSL
        run: |
            sudo apt-get install -y openssl
            
        
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.15.0

      - name: Install and Build Proyect
        run: |
             npm cache clean --force
             npm install
             npm run build

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist

      - name: Deploy to Claudia1991.github.io
        uses: actions/checkout@v2
        with:
          repository: 'Claudia1991/Claudia1991.github.io'
          token: ${{ secrets.API_TOKEN_GITHUB }}

      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: dist
