# This is a basic workflow to help you get started with Actions

name: Install and Build and Deploy

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  #pull_request:
   # branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
 # workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build-and-deploy"
  build-app:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v1
        
      - name: Install-Node
        uses: actions/setup-node@v1

      # Runs a single command using the runners shell
      - name: Install-Run
        run: |
             npm install
             npm run build

  deploy-app:

    needs: build-app

    runs-on: ubuntu-latest

    steps:
      -name: Deploying
      uses: Claudia1991/chat-box-vue@master
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      with:
        source-directory: 'dist/'
        destination-github-username: 'Claudia1991'
        destination-repository-name: 'Claudia1991.github.io'
        user-email: 'claudia.jara.py@gmail.com'
        commit-message: 'Update from $REPOSITORY_URL@commit'
