name: Install and Build and Deploy
on:
  push:
    branches: [ master ]
jobs:
  build-app:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install-Node
        uses: actions/setup-node@v1

      - name: Install-Run
        run: |
             npm install
             npm run build

      - name: Deploying
        id: push_directory
        uses: Claudia1991/chat-box-vue@master
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-directory: 'dist/'
          destination-github-username: 'Claudia1991'
          destination-repository-name: 'Claudia1991.github.io'
          user-email: 'claudia.jara.py@gmail.com'
          commit-message: 'Update from $REPOSITORY_URL@commit'
          
      - name: Test get variable generated
        run: echo $DESTINATION_CLONED_DIRECTORY
